name: timecard-kt
# Version gets set by version_setter.py
version: '0'
summary: Simple commandline time tracking program, written in Kotlin
description: |
  timecard-kt is a command line time tracking program
  written by a developer, for developers.
  Quick syntax allows time tracking to be easy, while also being customizable.
  Supports quarter-hour rounding, 24-hour time, and automatic cleanup.
  Configuration file is stored as a simple human readable YAML file.
  Data files are stored as simple JSON files that are developer readable.
base: core18
apps:
  timecard-kt:
    command: java -jar $SNAP/jar/timecard-kt_fat.jar
parts:
  timecard-kt:
    plugin: gradle
    gradle-options: [snapPrepare]
    source: https://github.com/Stephen-Hamilton-C/timecard-kt.git
    #source-tag: v$SNAPCRAFT_PROJECT_VERSION
    source-branch: snap
    stage-packages:
      - openjdk-11-jre
confinement: classic
