# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Deploy Debian Package

on:
  push:
    tags:
      - 'v*.*.*' # Release
    branches: [ dev ] # Snapshot

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Setup Debian Build Dependencies
      run: |
        sudo apt install build-essential devscripts debhelper
    - name: Build & Deploy Debian Package
      uses: gradle/gradle-build-action@v2
      with:
        arguments: debianDeploy
      
